spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
#    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: r2dbc:postgresql://postgres:postgres@localhost:5432/reactive
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 5000

logging:
  level:
    me:
      hl:
        webflux: DEBUG